#WAP TO PRINT INDEX AT WHICH A PARTICULAR VALUE EXIST.IF THE VALUE EXISTS AT MULTIPLE LOCATIONS IN THE LIST,THAN PRINT ALL THE INDICES.ALSO COUNT THE NUMBER OF TIMES THE VALUE IS REPEATED IN THE LIST.

#FORM A LIST OF FIRST CHARACTER OF EVERY WORD IN ANOTHER LIST.
